name: pomodoro
description: A timer app which utilizes pomodoro work technique
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  bloc: ^8.1.0
  custom_timer: ^0.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  # flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.17
  intl: ^0.17.0
  rive: ^0.10.1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"

flutter_native_splash:
  color: "#37474F"
  image: "assets/logo.png"
  branding: "assets/brand.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
